// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJb8NaUM9_BiM57IRuO3SNpOY6EsyfBwg',
    appId: '1:729942712872:web:af3b2851d4b2cfd5664b1d',
    messagingSenderId: '729942712872',
    projectId: 'ammar-brew-crew-50bd9',
    authDomain: 'ammar-brew-crew-50bd9.firebaseapp.com',
    storageBucket: 'ammar-brew-crew-50bd9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzH9JPhuMCWh4B4rH9NWlu_PWS7e-FMi0',
    appId: '1:729942712872:android:f38bdd42eb689ca8664b1d',
    messagingSenderId: '729942712872',
    projectId: 'ammar-brew-crew-50bd9',
    storageBucket: 'ammar-brew-crew-50bd9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi2QD6pD1ObGNjiQr0JptF4vgfeJ_AHyo',
    appId: '1:729942712872:ios:6da6837df4d4de67664b1d',
    messagingSenderId: '729942712872',
    projectId: 'ammar-brew-crew-50bd9',
    storageBucket: 'ammar-brew-crew-50bd9.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi2QD6pD1ObGNjiQr0JptF4vgfeJ_AHyo',
    appId: '1:729942712872:ios:6da6837df4d4de67664b1d',
    messagingSenderId: '729942712872',
    projectId: 'ammar-brew-crew-50bd9',
    storageBucket: 'ammar-brew-crew-50bd9.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
